### ISSUE TITLE
NameError: undefined local variable or method `fs' for #<MemFs::File:0x007f8feccb9a20>

### ISSUE THREAD

**Issue by mikz** [simonc/memfs#15]
try `MemFs.activate { File.open('file', 'w') { |f|f  << 'test' } }` 
and see

```
NameError: undefined local variable or method `fs' for #<MemFs::File:0x007f8feccb9a20>
from ruby-2.2.0/bundler/gems/memfs-c2f29bd47a74/lib/memfs/file.rb:243:in `initialize'
```

looks like `fs` is on class, not an instance

**Comment by simonc** [comment]
Hi, thank you for the feedback. Are you using a specific version or _master_ ?

**Comment by simonc** [comment]
I tried to reproduce the issue with a spec but the test passes :/

``` ruby
require 'spec_helper'

describe "Issue #15" do
  it 'supports File.open then <<' do
    expect{
      MemFs.activate { File.open('file', 'w') { |f|f << 'test' } } 
    }.not_to raise_error
  end
end
```

**Comment by simonc** [comment]
Ok, calling `rake console` inside the gem I can reproduce the issue. I'll try to find where it comes from.

**Comment by simonc** [comment]
Found it. It was due to `def fs` in _spec_helper.rb_ that was making calls to `fs` work during specs. I renamed it to `_fs` to expose the false positive specs and it revealed the same issue in `Dir`. Thank you very much!
