### ISSUE TITLE
Pry does not work

### ISSUE THREAD

**Issue by fpellanda** [simonc/memfs#25]
When running binding.pry when memfs is activated, pry cannot find the source code anymore.

Any idea how to fix that?

**Comment by simonc** [comment]
Hi @fpellanda. So sorry you're having a hard time with this.

A not yet published feature has landed on _master_ some time ago and it may be a suitable workaround, it's `MemFs.halt`.

```ruby
MemFs.halt { binding.pry }
```

Can you test this with _master_? If it works I release a new version and add it to the README :wink:

**Comment by fpellanda** [comment]
Thank you for the very fast answer. I've chosen another solution meanwile. But anyway, I think this would be a great feature to release! :+1:

**Comment by simonc** [comment]
I just tried the `MemFs.halt` solution and it works like a charm so I'll close this issue. Thanks for reporting it ☺️
