### ISSUE TITLE
uninitialized constant MemFs::Dir::Tmpname

### ISSUE THREAD

**Issue by neokyle1** [simonc/memfs#28]
I am running ruby 2.3.0 and memfs 1.0.0

When running the following test:

```ruby
  it "blah" do
    MemFs.activate do
      Tempfile.new('asd')
    end
  end
```

It results in the following error:

```
     Failure/Error: Tempfile.new('asd')

     NameError:
       uninitialized constant MemFs::Dir::Tmpname
```

**Comment by simonc** [comment]
Hi @neokyle1 sorry for not answering sooner, the Github notification went to my junk folder. Did you find a workaround in the mean time? I'll try to address the issue asap. Thanks for bringing this to my attention! ☺️

**Comment by neokyle1** [comment]
No problem. Sorry, I do not remember troubleshooting this that much. Looks like I ended up switching to fakefs for that project.
